services:
  postgres:
    image: postgres:15
    container_name: marketplace_postgres
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  migration-service:
    build:
      context: ./migration-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=marketplace
    volumes:
      - ./migration-service/migrations:/app/migrations

  user-service:
    build:
      context: ./user-service
    depends_on:
      migration-service:
        condition: service_completed_successfully
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=marketplace
      - JWT_SECRET=supersecretkey

  product-service:
    build:
      context: ./product-service
    depends_on:
      migration-service:
        condition: service_completed_successfully
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=marketplace

  order-service:
    build:
      context: ./order-service
    depends_on:
      migration-service:
        condition: service_completed_successfully
    ports:
      - "8083:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=marketplace

  cart-service:
    build:
      context: ./cart-service
    depends_on:
      migration-service:
        condition: service_completed_successfully
    ports:
      - "8084:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=marketplace
      - PRODUCT_SERVICE_URL=http://product-service:8080
      - ORDER_SERVICE_URL=http://order-service:8080

volumes:
  pgdata:
