services:
  postgres:
    image: postgres:15
    container_name: postgres_user
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  migration-service:
    build:
      context: ./migration-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=users
    volumes:
      - ./migration-service/migrations:/app/migrations

  user-service:
    build:
      context: ./user-service
    depends_on:
      migration-service:
        condition: service_completed_successfully
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=users
      - JWT_SECRET=supersecretkey

  product-service:
    build:
      context: ./product-service
    depends_on:
      migration-service:
        condition: service_completed_successfully
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=users

volumes:
  pgdata:
