POST http://localhost:8081/register 
contetn-type: "application/json"

{
    "name": "Alex",
    "email": "alex@email.com",
    "password": "secret"
}

###

POST http://localhost:8081/login 
Content-Type: "application/json"

{
    "email": "alex@email.com",
    "password":"secret"
}