POST http://localhost:8082/products
Content-Type: "application/json"

{
    "name":"MacBookM3",
    "description": "Laptop",
    "price": 2500
}

###

GET http://localhost:8082/products/2

###

GET http://localhost:8082/products/1

###

GET http://localhost:8082/products

###

DELETE http://localhost:8082/products/1
