POST http://localhost:8083/orders
Content-Type: "application/json"

{
    "user_id": 1,
    "product_ids": [1,2,3,4],
    "quantity": 4,
    "status": "",
    "total_price": 1600
}

###

DELETE  http://localhost:8083/orders/1 

###

GET http://localhost:8083/orders 

###

GET http://localhost:8083/orders/1 